version: "3.9"

services:
  load-balancer:
    build:
      context: .
      dockerfile: "LoadBalancer/Dockerfile"
    ports: 
      - 9020:80
  searchapi:
    build:
      context: .
      dockerfile: "SearchAPI/Dockerfile"
    ports:
      - "8080-8082:80"
    volumes:
      - "./EnronData:/data"
    deploy:
      replicas: 3
    depends_on:
      - load-balancer